theme: jekyll-theme-leap-day
title: ownCloud 10.2 Quickstart
description: This site provides information about installing and configuring the ownCloud server. It also provides details about accessing the Windows and mobile clients.
encoding: UTF-8
